### ISSUE TITLE
Your lib folder is missing on release 8.0.2

### ISSUE THREAD

**Issue by britzdylan** [Borewit/strtok3#1143]
As per the title

**Comment by d0c1989** [comment]
> As per the title

True. 


Took a while to understand what's going on, until downgrade to 8.0.1

**Comment by britzdylan** [comment]
@d0c1989 Same, however in my case it's a peer dependency so idk how to enforce it to use 8.0.1

**Comment by lonnie-smith** [comment]
I see this too!

**Comment by d0c1989** [comment]
I had it as peer also, i just did `npm i ***@***.***` and it worked.

**Comment by bluejack** [comment]
Also encountered this; downgraded to 8.0.1 and it works. Note in the npm distribution, the appropriate lib library appears to be under a token types directory. See two screenshots:

8.0.1: lib is a root folder of strtok3 (and exports points to it)

<img width="572" alt="Screenshot 2024-08-07 at 3 57 42 PM" src="https://github.com/user-attachments/assets/63730eed-ea92-4695-a47b-e813e7e37b8d">

8.0.2: lib is under token-types, but exports still points to a lib above this level.

<img width="639" alt="Screenshot 2024-08-07 at 3 59 52 PM" src="https://github.com/user-attachments/assets/727c498e-2de7-445e-96e5-e8cd42ad5532">

**Comment by dreamerblue** [comment]
Same here

**Comment by sdutwsl** [comment]
Same issue after I reinstall nvm for five times.

**Comment by Borewit** [comment]
Apologies, release was indeed incomplete, resolved in [v8.0.3](https://github.com/Borewit/strtok3/releases/tag/v8.0.3)
