### ISSUE TITLE
Move debug to devDependencies

### ISSUE THREAD

**Issue by chronoDave** [Borewit/strtok3#305]
I was going through my build and noticed that this package took up quite some space, only to realize it has a dependency which is twice as big as the package itself (namely `debug`). I looked through the source code and found that only `ReadStreamTokenizer.js` uses this package.

Is it possible for this package to be moved to `devDependencies`?

![Image reference](https://i.imgur.com/PnrpSnk.png)

**Comment by Borewit** [comment]
Currently [debug](https://github.com/visionmedia/debug) is [28,3 % of the package size](https://bundlephobia.com/result?p=strtok3@6.0.3).

Moving [debug](https://github.com/visionmedia/debug) is used for runtime log messages. Moving it `devDependencies` is not an option because it used runtime.

I checked how it used, it seems only to log the ignore method. I can live without that and remove the dependency. What is the size critical application you are working on?

**Comment by chronoDave** [comment]
Thank you for the quick response!

I'm currently working on [Doombox](https://github.com/chronoDave/Doombox), which is by no means a critical application (just a hobby project of mine). I was going through the bundled packages and noticed this package being somewhat bigger than the rest. If you don't want to remove the package that's absolutely fine! I was just curious as to why `strtok3` was so big.

**Comment by Borewit** [comment]
I dropped the dependency to debug in version [v6.0.4](https://github.com/Borewit/strtok3/releases/tag/v6.0.4). If for some reason , in the future, logging information runtime becomes important, I will not hesitate to re-enable it. Functionality is more important then size. 

> I'm currently working on [Doombox](https://github.com/chronoDave/Doombox), which is by no means a critical application (just a hobby project of mine). 

Sounds good. If you are using [music-metadata](https://github.com/Borewit/music-metadata), that will have the same dependency to [debug](https://github.com/visionmedia/debug). If you are not using [music-metadata](https://github.com/Borewit/music-metadata), you should check it out.

**Comment by chronoDave** [comment]
I am using music-metadata (excellent package!), so removing `debug` from this package didn't resolve much of the size issue now that I think of it... Should've looked into that before I opened this issue!
