### ISSUE TITLE
Source maps are referenced but not included in the NPM package

### ISSUE THREAD

**Issue by fungiboletus** [Borewit/strtok3#365]
Hi,

The files published on NPM contain references to JavaScript source map, such as `//# sourceMappingURL=index.js.map` at the end of the `index.js` file or `//# sourceMappingURL=FileTokenizer.js.map` at the end of `FileTokenizer.js`.

However, these files are not included in the NPM package. It's not a real issue but VSCode started to complain about it. See https://github.com/microsoft/vscode/issues/102042

The references to the source maps could be removed or the files could be included in the NPM package.

Thanks.

**Comment by Borewit** [comment]
If you have a good way to avoid generating these, I am open prevent these statements.

**Comment by fungiboletus** [comment]
Thanks !

**Comment by Borewit** [comment]
Can you please confirm @fungiboletus all of the references are gone in this module and the dependencies?
