### ISSUE TITLE
browsers support?

### ISSUE THREAD

**Issue by cainlevy** [Borewit/strtok3#825]
> A promise based streaming tokenizer for Node.js and browsers.

strtok3 says that it supports browsers but depends on core node modules. This makes it incompatible without polyfills which have become quite a struggle in create-react-app v5.

Any advice? How is this intended to work?

**Comment by Borewit** [comment]
It's a bit of a challenge to use this kind of modules in a browser environment. 
There are 2 types of modules available:
- CommonJS (CJS) version 6
- ECMAScript Module (ESM) version 7

With CJS you need to includes `strtok3/lib/core`, [example of strtok3 running in the browser](https://audio-tag-analyzer.netlify.app/).

With ESM it should automatically switch to core is browser context, but you can also import strttok3/core.

I think you need to polyfill:

1.   [buffer](https://www.npmjs.com/package/buffer)
2.   [readable-stream](https://www.npmjs.com/package/readable-stream)

Buffer has the required functions to parse binary files and do some text decoding functions. There is nothing like that in the browser, so you simply need this. 
The internal logic is still standardized in Node.js streams, in the future this may be replaces by web streams as both worlds slowly start to support that.

**Comment by Borewit** [comment]
Maybe ESM has room for improvement, it's fairly new. Ideally it automatically depends on the pollyfill libraries, so you don't have to pollyfill them via config files.

**Comment by Borewit** [comment]
PR, aiming to get rid of the Buffer dependency: #1074

**Comment by Borewit** [comment]
Available in [v7.1.0](https://github.com/Borewit/strtok3/releases/tag/v7.1.0)
